#!/bin/bash

# move this file to /usr/local/bin
# .gitattributes  like:
#    *.txt filter=dater
# and :
# git config filter.dater.smudge expand_date
# git config filter.dater.clean 'perl -pe "s/\\\$Date[^\\\$]*\\\$/\\\$Date\\\$/"'
last_date=`git log --pretty=format:"%ad" -1 | sed s/\\\+/\\\\\\\+/g | sed s/\\\s/\\\\\\\\\ /g `
sedstr='s/\$Date.*\$/\$Date:'$last_date'\$/'
while read line
do
    echo $line | sed "$sedstr"
done
